In [2]:
import nselib
import yfinance as yf
import pandas as pd
from nselib import capital_market
from nsetools import nse
from datetime import datetime,timedelta

In [3]:
nselib.trading_holiday_calendar()

,Product,tradingDate,weekDay,description,Sr_no
0,Corporate Bonds,22-Jan-2024,Monday,Special Holiday,1
1,Corporate Bonds,26-Jan-2024,Friday,Republic Day,2
2,Corporate Bonds,19-Feb-2024,Monday,Chatrapati Shivaji Maharaj Jayanti,3
3,Corporate Bonds,08-Mar-2024,Friday,Mahashivratri,4
4,Corporate Bonds,25-Mar-2024,Monday,Holi,5
...,...,...,...,...,...
16,Securities Lending & Borrowing Schemes,12-Oct-2024,Saturday,Dussehra,17
17,Securities Lending & Borrowing Schemes,01-Nov-2024,Friday,Diwali Laxmi Pujan*,18
18,Securities Lending & Borrowing Schemes,02-Nov-2024,Saturday,Diwali-Balipratipada,19
19,Securities Lending & Borrowing Schemes,15-Nov-2024,Friday,Gurunanak Jayanti,20
20,Securities Lending & Borrowing Schemes,25-Dec-2024,Wednesday,Christmas,21

In [4]:
capital_market.bhav_copy_equities('11-06-2024')

,SYMBOL,SERIES,OPEN,HIGH,LOW,CLOSE,LAST,PREVCLOSE,TOTTRDQTY,TOTTRDVAL,TIMESTAMP,TOTALTRADES
0,0MOFSL27,N3,990.00,992.00,990.00,990.05,990.05,987.00,500,4.951175e+05,11-JUN-2024,3
1,1003ISFL28,N4,995.00,996.10,994.97,996.00,996.00,992.87,203,2.021550e+05,11-JUN-2024,7
2,1015ECL29,NR,1003.90,1003.99,1000.00,1002.90,1002.90,1003.81,710,7.110432e+05,11-JUN-2024,23
3,1018GS2026,GS,112.90,112.90,112.90,112.90,112.90,113.00,3775,4.261975e+05,11-JUN-2024,5
4,1025IHF34,Z8,930.00,960.00,930.00,960.00,960.00,930.00,415,3.865500e+05,11-JUN-2024,22
...,...,...,...,...,...,...,...,...,...,...,...,...
2753,ZTECH,ST,127.55,127.55,127.55,127.55,127.55,121.50,67200,8.571360e+06,11-JUN-2024,31
2754,ZUARI,EQ,190.00,194.19,187.50,189.52,189.50,186.81,429310,8.182017e+07,11-JUN-2024,8812
2755,ZUARIIND,EQ,317.55,324.00,311.40,320.90,322.00,315.10,129179,4.124617e+07,11-JUN-2024,7733
2756,ZYDUSLIFE,EQ,1087.50,1093.50,1080.15,1084.85,1086.55,1086.05,1554675,1.690251e+09,11-JUN-2024,90144
2757,ZYDUSWELL,EQ,1904.10,1944.45,1851.00,1919.95,1920.00,1882.25,111450,2.144372e+08,11-JUN-2024,12509

In [5]:
capital_market.bhav_copy_with_delivery('11-06-2024')

,SYMBOL,SERIES,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,PREV_CLOSE,TTL_TRD_QNTY,TURNOVER_LACS,NO_OF_TRADES,DELIV_QTY,DELIV_PER,DATE1
0,1018GS2026,GS,112.90,112.90,112.90,112.90,113.00,3775,4.26,5,3775,100.00,11-Jun-2024
1,20MICRONS,EQ,183.90,186.15,179.00,180.79,181.74,155858,285.94,5436,85354,54.76,11-Jun-2024
2,21STCENMGM,BE,52.54,52.54,52.54,52.54,51.51,2469,1.30,18,-,-,11-Jun-2024
3,360ONE,EQ,800.00,800.00,778.00,780.75,792.20,363545,2851.52,32849,220305,60.60,11-Jun-2024
4,3IINFOLTD,EQ,36.10,38.34,36.10,37.55,36.75,2266353,846.97,9328,717036,31.64,11-Jun-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2574,ZTECH,ST,127.55,127.55,127.55,127.55,121.50,67200,85.71,31,67200,100.00,11-Jun-2024
2575,ZUARI,EQ,190.00,194.19,187.50,189.52,186.81,429310,818.20,8812,209403,48.78,11-Jun-2024
2576,ZUARIIND,EQ,317.55,324.00,311.40,320.90,315.10,129179,412.46,7733,62587,48.45,11-Jun-2024
2577,ZYDUSLIFE,EQ,1087.50,1093.50,1080.15,1084.85,1086.05,1554675,16902.51,90144,1081855,69.59,11-Jun-2024
2578,ZYDUSWELL,EQ,1904.10,1944.45,1851.00,1919.95,1882.25,111450,2144.37,12509,77031,69.12,11-Jun-2024

In [6]:
capital_market.block_deals_data(period='1M')

,Date,Symbol,SecurityName,ClientName,Buy/Sell,QuantityTraded,TradePrice/Wght.Avg.Price,Remarks
0,27-MAY-2024,LUMAXTECH,Lumax Auto Technologies L,ALBULA INVESTMENT FUND LTD,SELL,"6,06,000",478.00,-
1,27-MAY-2024,LUMAXTECH,Lumax Auto Technologies L,AMARA PARTNERS GROWTH FUND I,BUY,"6,06,000",478.00,-
2,04-JUN-2024,HGS,Hinduja Global Sols Ltd,AASIA EXPORTS,SELL,"11,60,000",804.00,-
3,04-JUN-2024,HGS,Hinduja Global Sols Ltd,HINDUJA GROUP LIMITED,BUY,"11,60,000",804.00,-
4,06-JUN-2024,PONNIERODE,Ponni Sugars (Erode) Limi,EMPLOYEES RETIREMENT PLAN OF DUKE UNIVERSITY,SELL,"19,000",422.00,-
...,...,...,...,...,...,...,...,...
107,26-JUN-2024,SHARDAMOTR,Sharda Motor Inds Ltd,HSBC MUTUAL FUND,BUY,"1,85,356","1,996.10",-
108,26-JUN-2024,SHARDAMOTR,Sharda Motor Inds Ltd,ICICI PRUDENTIAL MUTUAL FUND,BUY,"5,13,488","1,996.10",-
109,26-JUN-2024,SHARDAMOTR,Sharda Motor Inds Ltd,MALA RELAN,SELL,"25,00,000","1,996.10",-
110,26-JUN-2024,SHARDAMOTR,Sharda Motor Inds Ltd,NIPPON INDIA MUTUAL FUND,BUY,"4,13,295","1,996.10",-
111,26-JUN-2024,SHARDAMOTR,Sharda Motor Inds Ltd,PGIM INDIA MUTUAL FUND,BUY,"50,192","1,996.10",-

In [7]:
import yfinance as yf
def fetch_historical_data(symbol, period='1mo'):
    stock = yf.Ticker(symbol)
    data = stock.history(period=period)
    return data

    
symbol = 'SBIN.NS'  
period = '1mo'      

historical_data = fetch_historical_data(symbol, period)
if not historical_data.empty:
    print(historical_data)
else:
    print(f"No data found for symbol {symbol} in the period {period}")

                                 Open        High         Low       Close  \
Date
2024-05-27 00:00:00+05:30  832.599976  839.400024  823.000000  833.700012
2024-05-28 00:00:00+05:30  835.700012  840.700012  823.299988  831.150024
2024-05-29 00:00:00+05:30  828.400024  834.450012  819.299988  822.650024
2024-05-30 00:00:00+05:30  821.400024  836.000000  819.299988  825.849976
2024-05-31 00:00:00+05:30  830.700012  835.000000  817.099976  830.349976
2024-06-03 00:00:00+05:30  863.549988  912.000000  856.750000  905.650024
2024-06-04 00:00:00+05:30  897.000000  897.000000  731.950012  775.200012
2024-06-05 00:00:00+05:30  790.750000  795.000000  744.049988  789.750000
2024-06-06 00:00:00+05:30  800.000000  833.349976  796.000000  816.950012
2024-06-07 00:00:00+05:30  819.900024  831.500000  810.500000  829.950012
2024-06-10 00:00:00+05:30  834.150024  845.450012  829.200012  831.799988
2024-06-11 00:00:00+05:30  836.000000  839.599976  829.049988  835.549988
2024-06-12 00:00:00+05:30  837.000000  845.549988  833.000000  839.099976
2024-06-13 00:00:00+05:30  845.000000  845.900024  836.099976  843.900024
2024-06-14 00:00:00+05:30  845.000000  849.900024  835.099976  839.200012
2024-06-18 00:00:00+05:30  841.549988  851.500000  840.250000  844.900024
2024-06-19 00:00:00+05:30  846.799988  860.599976  841.000000  852.599976
2024-06-20 00:00:00+05:30  853.000000  853.099976  842.349976  843.750000
2024-06-21 00:00:00+05:30  844.900024  848.049988  828.599976  836.299988
2024-06-24 00:00:00+05:30  831.500000  836.000000  821.049988  832.700012
2024-06-25 00:00:00+05:30  837.000000  845.849976  834.299988  842.250000
2024-06-26 00:00:00+05:30  839.849976  848.799988  836.000000  845.349976

                              Volume  Dividends  Stock Splits
Date
2024-05-27 00:00:00+05:30   12295193        0.0           0.0
2024-05-28 00:00:00+05:30   13818893        0.0           0.0
2024-05-29 00:00:00+05:30   14518232        0.0           0.0
2024-05-30 00:00:00+05:30   17818705        0.0           0.0
2024-05-31 00:00:00+05:30   22267336        0.0           0.0
2024-06-03 00:00:00+05:30   64269020        0.0           0.0
2024-06-04 00:00:00+05:30  122381193        0.0           0.0
2024-06-05 00:00:00+05:30   74256082        0.0           0.0
2024-06-06 00:00:00+05:30   40555649        0.0           0.0
2024-06-07 00:00:00+05:30   25061284        0.0           0.0
2024-06-10 00:00:00+05:30   16725508        0.0           0.0
2024-06-11 00:00:00+05:30   14754408        0.0           0.0
2024-06-12 00:00:00+05:30   15071442        0.0           0.0
2024-06-13 00:00:00+05:30   12523972        0.0           0.0
2024-06-14 00:00:00+05:30   12903496        0.0           0.0
2024-06-18 00:00:00+05:30   14929083        0.0           0.0
2024-06-19 00:00:00+05:30   32925140        0.0           0.0
2024-06-20 00:00:00+05:30   13985352        0.0           0.0
2024-06-21 00:00:00+05:30   18990090        0.0           0.0
2024-06-24 00:00:00+05:30   12715254        0.0           0.0
2024-06-25 00:00:00+05:30   20917530        0.0           0.0
2024-06-26 00:00:00+05:30   16279952        0.0           0.0