In [2]:
import nselib
from nselib import capital_market
from nsetools import nse
from datetime import datetime

In [3]:
nselib.trading_holiday_calendar()

,Product,tradingDate,weekDay,description,Sr_no
0,Corporate Bonds,22-Jan-2024,Monday,Special Holiday,1
1,Corporate Bonds,26-Jan-2024,Friday,Republic Day,2
2,Corporate Bonds,19-Feb-2024,Monday,Chatrapati Shivaji Maharaj Jayanti,3
3,Corporate Bonds,08-Mar-2024,Friday,Mahashivratri,4
4,Corporate Bonds,25-Mar-2024,Monday,Holi,5
...,...,...,...,...,...
16,Securities Lending & Borrowing Schemes,12-Oct-2024,Saturday,Dussehra,17
17,Securities Lending & Borrowing Schemes,01-Nov-2024,Friday,Diwali Laxmi Pujan*,18
18,Securities Lending & Borrowing Schemes,02-Nov-2024,Saturday,Diwali-Balipratipada,19
19,Securities Lending & Borrowing Schemes,15-Nov-2024,Friday,Gurunanak Jayanti,20
20,Securities Lending & Borrowing Schemes,25-Dec-2024,Wednesday,Christmas,21

In [6]:
capital_market.bhav_copy_equities('11-06-2024')

,SYMBOL,SERIES,OPEN,HIGH,LOW,CLOSE,LAST,PREVCLOSE,TOTTRDQTY,TOTTRDVAL,TIMESTAMP,TOTALTRADES
0,0MOFSL27,N3,990.00,992.00,990.00,990.05,990.05,987.00,500,4.951175e+05,11-JUN-2024,3
1,1003ISFL28,N4,995.00,996.10,994.97,996.00,996.00,992.87,203,2.021550e+05,11-JUN-2024,7
2,1015ECL29,NR,1003.90,1003.99,1000.00,1002.90,1002.90,1003.81,710,7.110432e+05,11-JUN-2024,23
3,1018GS2026,GS,112.90,112.90,112.90,112.90,112.90,113.00,3775,4.261975e+05,11-JUN-2024,5
4,1025IHF34,Z8,930.00,960.00,930.00,960.00,960.00,930.00,415,3.865500e+05,11-JUN-2024,22
...,...,...,...,...,...,...,...,...,...,...,...,...
2753,ZTECH,ST,127.55,127.55,127.55,127.55,127.55,121.50,67200,8.571360e+06,11-JUN-2024,31
2754,ZUARI,EQ,190.00,194.19,187.50,189.52,189.50,186.81,429310,8.182017e+07,11-JUN-2024,8812
2755,ZUARIIND,EQ,317.55,324.00,311.40,320.90,322.00,315.10,129179,4.124617e+07,11-JUN-2024,7733
2756,ZYDUSLIFE,EQ,1087.50,1093.50,1080.15,1084.85,1086.55,1086.05,1554675,1.690251e+09,11-JUN-2024,90144
2757,ZYDUSWELL,EQ,1904.10,1944.45,1851.00,1919.95,1920.00,1882.25,111450,2.144372e+08,11-JUN-2024,12509